# Generated by Django 3.0.4 on 2020-05-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correlative', models.IntegerField()),
                ('display', models.BooleanField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('required', models.BooleanField(blank=True, null=True)),
                ('selected', models.BooleanField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
    ]
