# Generated by Django 3.0.4 on 2020-05-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Useruvg',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
                ('enabled', models.BooleanField()),
                ('firstname', models.CharField(max_length=50)),
                ('lastpasswordresetdate', models.DateTimeField()),
                ('lastname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'useruvg',
                'managed': False,
            },
        ),
    ]
