# Generated by Django 3.0.4 on 2020-05-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('id_father', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'answers',
                'managed': False,
            },
        ),
    ]
