# Generated by Django 3.0.4 on 2020-05-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('image', models.CharField(blank=True, max_length=10000, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'advice',
                'managed': False,
            },
        ),
    ]
